In [11]:
import numpy as np

a=np.array([[1,2,3],
    [4,5,6],
    [7,8,9]])
b=np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

c=np.dot(a,b)

print('*'*30)
print(a)
print('*'*30)
print(a)
print('*'*30)

print(c)
print('*'*30)
d=np.transpose(a)
print(d)
print('*'*30)


******************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]
******************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]
******************************
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
******************************
[[1 4 7]
 [2 5 8]
 [3 6 9]]
******************************
